spring:
  #application-secret.yml import
  config:
    import: application-secret.yml
  application:
    name: board
  #redis
  redis:
    host: localhost
    port: 6379
  profiles:
    include: secret
  #sql
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  #thymeleaf
  devtools:
    livereload:
      enabled: ture
    restart:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace